name: bookprinter
version: '${project.version}'
main: com.majesticrise.bookprinter.BookPrinter
api-version: '1.21'
load: STARTUP
softdepend: [Vault]  # 新增：软依赖 Vault
folia-supported: true #新增了Folia支持,所以这里声明支持Folia
authors: [ majesticrise ]
description: 支持Paper和Folia的现代化TXT转Book插件，支持RGB渐变与双模式分页

commands:
  bookprinter:
    description: 书籍打印主命令
    usage: /bookprinter <buy|print|reload|info> [参数...]
    aliases: [bp, printbook]
permissions:
  bookprinter.print:
    description: 允许使用 print 子命令（管理员打印书本）
    default: op
  bookprinter.buy:
    description: 允许使用 buy 子命令（玩家购买书本）
    default: true
  bookprinter.reload:
    description: 允许重载插件配置
    default: op
  bookprinter.info:
    description: 允许查看插件运行信息
    default: op