name: bookprinter
version: '1.0'
main: com.majesticrise.bookprinter.BookPrinter
api-version: '1.21'
load: STARTUP
authors: [ majesticrise ]
description: book
website: https://space.bilibili.com/3493114226411557
commands:
  bookprinter:
    description: 将服务器上的 TXT 文件转换为已写的书
    usage: /bookprinter <文件名或绝对路径> [署名]
    permission: bookprinter.use
permissions:
  bookprinter.use:
    description: 允许使用 /bookprinter
    default: op